Repository tanganke/fusion_bench, pull requests merged in 2024-12, with the labels that each got.

#48 merge develop into main
  docs/modelpool/nyuv2.md
  fusion_bench/dataset/llama/stanford_shp.py
  fusion_bench/method/pruning/llama_magnitude_prune.py
  fusion_bench/method/pruning/llama_random_prune.py
  fusion_bench/mixins/clip_classification.py
Labels: size/S

#49 add method 'surgery'
  config/method/surgery/adamerging_surgery.yaml
  fusion_bench/compat/method/__init__.py
  fusion_bench/compat/method/base_algorithm.py
  fusion_bench/method/adamerging/layer_wise_adamerging.py
  fusion_bench/method/adamerging/min_norm_solvers.py
  fusion_bench/method/surgery/__init__.py
  fusion_bench/method/surgery/clip_layer_wise_adamerging_surgery.py
  fusion_bench/mixins/clip_classification.py
  fusion_bench/models/hf_clip.py
  fusion_bench/models/surgery/surgerymodelwrapper.py
  fusion_bench/models/wrappers/layer_wise_fusion.py
  fusion_bench/models/wrappers/task_wise_fusion.py
  fusion_bench/scripts/cli.py
  fusion_bench/taskpool/clip_vision/taskpool.py
  fusion_bench/utils/type.py
Labels: size/XL

#50 update the version number
  pyproject.toml
Labels: size/XS

#52 Update TSVM.py
  fusion_bench/method/task_singular_vector/TSVM.py
Labels: size/XS

#53 Update cifar100.yaml
  config/dataset/image_classification/test/cifar100.yaml
Labels: size/XS

#54 Update cifar100.yaml
  config/dataset/image_classification/train/cifar100.yaml
Labels: size/XS

#55 Create download_TALL20_models.sh
  config/model/clip-vit/download_TALL20_models.sh
Labels: size/XS

#56 Update clip_finetune.py
  fusion_bench/method/classification/clip_finetune.py
Labels: size/S

#57 Update lightning_fabric.py
  fusion_bench/mixins/lightning_fabric.py
Labels: size/XS
