Repository tanganke/fusion_bench, pull requests merged in 2025-03, with the labels that each got.

#78 Add DOGE_TA and DOGE_AM
  config/method/DOGE_TA/DOGE_TA.yaml
  fusion_bench/compat/method/__init__.py
  fusion_bench/method/DOGE_TA/DOGE_TA.py
  fusion_bench/method/DOGE_TA/__init__.py
  fusion_bench/method/DOGE_TA/clip_layer_wise_adamerging.py
  fusion_bench/method/DOGE_TA/layer_wise_adamerging.py
  fusion_bench/method/__init__.py
  fusion_bench/models/wrappers/layer_wise_fusion_doge_ta.py
Labels: size/XXL

#79 V0.2.11
  examples/clip_finetune/convert_ckpt.ipynb
  examples/clip_finetune/task_arithmetic.ipynb
  examples/iterative_sparselo_pruning/lower_bound_of_rank.ipynb
  examples/smile_upscaling/clip-vit-base-patch32-ablations-topk.ipynb
  examples/smile_upscaling/clip-vit-base-patch32.ipynb
  examples/smile_upscaling/clip-vit-base-patch32_single-task_projection-merging.ipynb
  examples/smile_upscaling/clip-vit-large-patch14.ipynb
  fusion_bench/method/DOGE_TA/__init__.py
  fusion_bench/method/concrete_subspace/__init__.py
  fusion_bench/method/concrete_subspace/clip_post_defense.py
  fusion_bench/method/concrete_subspace/clip_safe_concrete_adamerging.py
  fusion_bench/method/isotropic_merging/__init__.py
  fusion_bench/method/isotropic_merging/iso.py
  fusion_bench/method/task_singular_vector/TSVM.py
  pyproject.toml
  tests/test_depth_upscaling.py
  tests/test_utils/test_state_dict_arithmetic.py
Labels: size/L

#80 remove redundant code, fix bug of method AdaMerging+DOGE
  fusion_bench/models/wrappers/layer_wise_fusion.py
  fusion_bench/models/wrappers/layer_wise_fusion_doge_ta.py
Labels: size/L

#81 change DOGE_TA to doge_ta
  config/method/doge_ta/doge_ta.yaml
  fusion_bench/compat/method/__init__.py
  fusion_bench/method/DOGE_TA/__init__.py
  fusion_bench/method/__init__.py
  fusion_bench/method/doge_ta/__init__.py
  fusion_bench/method/doge_ta/clip_layer_wise_adamerging.py
  fusion_bench/method/doge_ta/doge_ta.py
  fusion_bench/method/doge_ta/layer_wise_adamerging.py
Labels: size/S
