Repository tanganke/fusion_bench, pull requests merged in 2025-05, with the labels that each got.

#102 Add integration with lm-eval-harness
  README.md
  config/taskpool/LMEvalHarnessTaskPool/lm_eval.yaml
  docs/taskpool/lm_eval_harness.md
  fusion_bench/taskpool/__init__.py
  fusion_bench/taskpool/lm_eval_harness/__init__.py
  fusion_bench/taskpool/lm_eval_harness/taskpool.py
  mkdocs.yml
Labels: size/L

#104 Update docs and modelpool configs for llm model merging
  README.md
  config/modelpool/CausalLMPool/mergebench/Llama-3.1-8B-Instruct.yaml
  config/modelpool/CausalLMPool/mergebench/Llama-3.1-8B.yaml
  config/modelpool/CausalLMPool/mergebench/Llama-3.2-3B-Instruct.yaml
  config/modelpool/CausalLMPool/mergebench/Llama-3.2-3B.yaml
  config/modelpool/CausalLMPool/mergebench/gemma-2-2b-it.yaml
  config/modelpool/CausalLMPool/mergebench/gemma-2-2b.yaml
  config/modelpool/CausalLMPool/mergebench/gemma-2-9b-it.yaml
  config/modelpool/CausalLMPool/mergebench/gemma-2-9b.yaml
  docs/README.md
  docs/modelpool/causal_lm.md
  docs/modelpool/llama_models.md
  fusion_bench/modelpool/causal_lm/causal_lm.py
  mkdocs.yml
Labels: size/L

#105 Update to v0.2.15
  pyproject.toml
Labels: size/XS

#106 add lazy state dict and modelpool
  fusion_bench/modelpool/lazy_state_dict_pool.py
  fusion_bench/utils/__init__.py
  fusion_bench/utils/lazy_state_dict.py
Labels: size/L

#107 Update data.py--fixing logic that causes TypeError
  fusion_bench/utils/data.py
Labels: size/XS

#108 Update README.md
  README.md
Labels: documentation, size/XS
