Repository tanganke/fusion_bench, pull requests merged in 2025-01, with the labels that each got.

#58 Merge develop into main
  fusion_bench/method/surgery/clip_layer_wise_adamerging_surgery.py
  fusion_bench/method/task_singular_vector/TSVM.py
  fusion_bench/method/task_singular_vector/__init__.py
  fusion_bench/method/task_singular_vector/utils/TSVM_utils.py
  fusion_bench/programs/fabric_fusion_program.py
Labels: size/M

#61 Update clip_dataset.py
  fusion_bench/dataset/clip_dataset.py
Labels: size/XS

#62 Update pyproject.toml
  pyproject.toml
Labels: size/XS

#66 Update slerp.py
  fusion_bench/method/slerp/slerp.py
Labels: size/XS

#70 update TSVM_utils
  fusion_bench/method/task_singular_vector/utils/TSVM_utils.py
Labels: size/L

#68 Update README.md
  README.md
Labels: size/M

#71 Update version to 0.2.9
  pyproject.toml
Labels: size/XS
