Repository tanganke/fusion_bench, pull requests merged in 2025-04, with the labels that each got.

#85 merge develop into main
  docs/algorithms/adamerging.md
  docs/modelpool/clip_vit.md
  examples/opcm/clip_vit_adamerging.sh
  examples/opcm/config/modelpool/clip-vit-base-patch32-round_1.yaml
  examples/opcm/config/modelpool/clip-vit-base-patch32-round_2.yaml
  examples/opcm/config/modelpool/clip-vit-base-patch32-round_3.yaml
  examples/opcm/config/modelpool/clip-vit-base-patch32-round_4.yaml
  examples/opcm/config/modelpool/clip-vit-base-patch32-round_5.yaml
  examples/opcm/config/modelpool/clip-vit-base-patch32-round_6.yaml
  examples/opcm/config/modelpool/clip-vit-base-patch32-round_7.yaml
  fusion_bench/dataset/fer2013.py
  fusion_bench/method/adamerging/clip_layer_wise_adamerging.py
  fusion_bench/method/doge_ta/clip_layer_wise_adamerging.py
  fusion_bench/method/opcm/opcm.py
  fusion_bench/method/opcm/task_arithmetic.py
  fusion_bench/method/opcm/ties_merging.py
Labels: size/XL

#86 Add FW-Merging in community news.
  README.md
Labels: size/XS

#87 Update README.md
  README.md
Labels: size/XS

#88 Update pyproject.toml
  pyproject.toml
Labels: size/XS

#91 Delete examples/smile_upscaling/cummulative_explained_variance.ipynb
  examples/smile_upscaling/cummulative_explained_variance.ipynb
Labels: size/L

#95 add utils for openclip models
  examples/open_clip/.gitignore
  examples/open_clip/convert.sh
  examples/open_clip/convert_openclip_model.py
  examples/open_clip/requirements.txt
  examples/open_clip/src/__init__.py
  examples/open_clip/src/convert_open_clip_to_hf.py
  examples/open_clip/src/modeling.py
  examples/open_clip/src/utils.py
  fusion_bench/method/adamerging/clip_task_wise_adamerging.py
  fusion_bench/models/open_clip/__init__.py
  fusion_bench/models/open_clip/modeling.py
  fusion_bench/models/open_clip/utils.py
  fusion_bench/models/open_clip/variables_and_paths.py
  fusion_bench/utils/data.py
  fusion_bench/utils/devices.py
  fusion_bench/utils/misc.py
Labels: size/XXL

#97 Enhance compatibility with newer version of OpenCLIP
  config/modelpool/OpenCLIPVisionModelPool/ViT-B-32_TA_cars_dtd.yaml
  config/modelpool/OpenCLIPVisionModelPool/ViT-B-32_TA_sun397_cars.yaml
  config/modelpool/OpenCLIPVisionModelPool/ViT-B-32_TA_sun397_dtd.yaml
  fusion_bench/method/pwe_moe/openclip_pwe_moe.py
  fusion_bench/modelpool/openclip_vision/modelpool.py
  fusion_bench/utils/packages.py
Labels: size/L
